Go solutions
fxzuz/programming_skills_test pull request #1
Opened 2017-02-14 20:14 UTC by evbogdanov

2017-02-14 20:20 UTC, sergeyklay commented
Awesome!

2017-02-15 12:13 UTC, sergeyklay requested changes

2017-02-15 12:13 UTC, sergeyklay commented on .gitignore
> +*.DS_Store
Please do not use this ignore file to define platform specific files.

For these purposes create a global `.gitignore` file, which is a list of rules
for ignoring files in every Git repository on your computer.

https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

2017-02-18 16:49 UTC, sergeyklay commented
@evbogdanov Looks like this repo is abandoned. I've created a fork and merged your Go solutions: https://github.com/sergeyklay/programming_skills_test

2017-02-18 17:00 UTC, evbogdanov commented
@sergeyklay Awesome, keep up the good work!

2017-02-18 17:14 UTC, merged